---
title: "R vs SAS Confidence Intervals for Proportions"
---

## Introduction

See the [summary page](../method_summary/ci_for_prop_intro.html) for general introductory information on confidence intervals for proportions, including the principles underlying the most common methods.

For more technical derivation of methods for comparing independent proportions, see the corresponding [SAS page](https://psiaims.github.io/CAMIS/SAS/ci_for_2indep_prop.html).

The tables below provide an overview of findings from R & SAS, for calculation of CIs for 2 independent sample proportions.

## General Comparison Table For Two Independent Samples Proportions

+--------------------------------------------------------------------+--------------------------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Analysis of Two Independant Sample Proportions                     | Supported in R                                                     | Supported in SAS | Results Match                                                                                                                                                                                                                                 |
+====================================================================+====================================================================+==================+===============================================================================================================================================================================================================================================+
| Normal approximation (Wald Method)                                 | Yes {DescTools}                                                    | Yes (default)    | Yes and results match by hand calculation                                                                                                                                                                                                     |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | `BinomDiffCI(..,method=c("wald"))`                                 |                  | **Warning** The documentation for stats::prop.test which is used in {cardx} says it's using newcombe method. However, the results match the Normal Approximation (wald) method. Hence it is reccomended to use {DescTools} instead of {cardx} |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | Yes {cardx} `ard_stats_prop_test function` uses `stats::prop.test` |                  |                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------+--------------------------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Normal approximation (Wald Method) with continuity correction      | Yes {DescTools}                                                    | Yes              | Yes                                                                                                                                                                                                                                           |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | `BinomDiffCI(..,method=c("waldcc"))`                               |                  | **Warning** that documentation for stats::prop.test says it's using newcombe method. However, the results match the Normal Approximation (wald) method.                                                                                       |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | Yes {cardx} as per above but with correct=TRUE                     |                  |                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------+--------------------------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Wilson (Score, Altman, Newcombe) method                            | Yes {DescTools}                                                    | Yes              | Yes and results match by hand calculation                                                                                                                                                                                                     |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | `BinomDiffCI(..,method=c("score"))`                                |                  |                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------+--------------------------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Wilson (Score, Altman, Newcombe) method with continuity correction | Yes {DescTools}                                                    | Yes              | Yes                                                                                                                                                                                                                                           |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | `BinomDiffCI(..,method=c("scorecc"))`                              |                  |                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------+--------------------------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Agresti-Caffo                                                      | Yes {DescTools}                                                    | Yes              | Yes                                                                                                                                                                                                                                           |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | `BinomDiffCI(..,method=c("ac"))`                                   |                  |                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------+--------------------------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Hauck-Anderson                                                     | Yes {DescTools}                                                    | Yes              | Yes                                                                                                                                                                                                                                           |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | `BinomDiffCI(..,method=c("ha"))`                                   |                  |                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------+--------------------------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miettinen-Nurminen                                                 | Yes {DescTools}                                                    | Yes              | Yes                                                                                                                                                                                                                                           |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | `BinomDiffCI(..,method=c("mn"))`                                   |                  |                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------+--------------------------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Prerequisites: R Packages

See the [R page](https://psiaims.github.io/CAMIS/R/ci_for_prop.html) for more detail.

```{r}
# Example R packages required
library(cardx)
library(ratesci)
```
